version: '2'

services:
  mysql:
    image: 'bitnami/mysql:latest'
    container_name: appctx-example-mysql
    ports:
    - 3306:3306
    volumes:
    - appctx-example-db-data:/bitnami/mysql/data
    environment:
    - MYSQL_USER=user
    - MYSQL_DATABASE=db
    - MYSQL_PASSWORD=somepass
    - MYSQL_ROOT_PASSWORD=somepass
volumes:
  appctx-example-db-data:
